grafana:
  service:
    type: ClusterIP
  persistence:
    enabled: false

prometheus:
  prometheusSpec:
    retention: 7d

alertmanager:
  enabled: true

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false