apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-control-service
  namespace: olivelive
spec:
  template:
    spec:
      containers:
        - name: live-control-service
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi